spring:
  application:
    name: discodeit

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

discodeit:
  repository:
    type: file
    base-directory: user.dir
    file-directory: .discodeit/data/
    extension: .ser

