server:
  port: 8080
spring:
  application:
    name: discodeit
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:commonDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    root: info

repository:
  type: file     # jcf | file
  file-directory: .discodeit