spring:
  profiles:
    active: dev
  application: # 애플리케이션 기본 설정
    name: discodeit  # 애플리케이션 이름 설정
  servlet:
    multipart: # multipart 파일 업로드 설정
      max-file-size: 10MB  # 파일 하나 최대 크기
      max-request-size: 30MB # 요청당 최대 크기
  jpa: # JPA, Hibernate 설정
    hibernate:
      ddl-auto: validate  # 데이터베이스 테이블과 엔티티 매핑 검증만 수행, 운영환경에서 일반적으로 validate 사용
    properties:
      hibernate:
        format_sql: true  # sql 보기 좋게 포맷팅
    open-in-view: false
    # 기본적으로 스프링부트는 영속성 컨텍스트를 요청이 끝날 때까지 유지
    # 비활성화 시 서비스 레이어에서만 영속성 컨텍스트 사용 가능
    # 성능 최적화에 도움됨 (특히, Lazy Loading 관련 문제 사전 방지)

logging:
  level:
    root: info  # 기본 로깅 레벨

discodeit: # 파일 저장소 설정
  storage:
    type: local # 파일 저장소 타입 local로 설정
    local:
      root-path: .discodeit/storage # 로컬 저장소 경로