server:
  port: 8081

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

logging:
  level:
    root: info
    com.sprint.mission : info


