server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  file:
    path: ./logs
    name: app-prod
  logback:
    rollingpolicy:
      max-history: 30
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "loggers"
  endpoint:
    health:
      show-details: "ALWAYS"
  info:
    env:
      enabled: true

jwt:
  secret: ${JWT_SECRET}

info:
  name: ${spring.application.name}
  version: ${spring.application.version}
  java:
    version: ${java.version}
  spring-boot:
    version: ${spring.boot.version}
  profile: ${spring.profiles.active}