spring:
  application:
    name: discodeit
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
      enabled: true

discodeit:
  repository:
    type: file  # jcf or file
    file-directory: .discodeit

file:
  dir: C:/Users/leeco/Desktop/codeit_sprint/mission/1-sprint-mission/data_storage/