spring:
  application:
    name: discodeit

file:
  binaryContent-json-path: "tmp/binaryContents.json"
  channel-json-path: "tmp/channels.json"
  message-json-path: "tmp/messages.json"
  readStatus-json-path: "tmp/readStatuses.json"
  user-json-path: "tmp/users.json"
  userStatus-json-path: "tmp/userStatuses.json"