spring:
  application:
    name: 1-sprint-mission

file:
  path:
    user: data/users.dat
    channel: data/channels.dat
    message: data/messages.dat
    binarycontent: data/binarycontents.dat
    readstatus: data/readstatus.dat
    userstatus: data/userstatus.dat

discodeit:
  repository:
    type: file
