spring:
  profiles:
    active: Jcf

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ""
    driver-class-name: ""
    username: ""
    password: ""
  servlet:
    multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
# Multipart 요청 허용