spring:
  config:
    activate:
      on-profile: prod

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#            default_batch_fetch_size: 100