server:
  port: 8080 # 웹 요청(HTTP)을 받을 서버 API 포트. http://localhost:8080으로 접속가능

spring:
  datasource: # 5432는 PostgreSQL 데이터베이스 서버가 사용하는 포트
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user # db 사용자 이름
    password: discodeit1234 # db 비밀번호
  jpa:
    properties:
      hibernate:
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:9090

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

