spring:
  application:
    name: discodeit

discodeit:
  repository:
    type: jcf # jcf | file
    file-directory: temp

server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true