server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  discodeit:
    repository:
      type: jcf
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  web:
    resources:
      cache:
        period: 0