spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

repository:
  type : jcf  # jcf or file

