spring:
  application:
    name: discodeit

discodeit:
  repository:
    type: file  #jcf | file
    file-directory: .discodeit


logging:
  level:
    org.springframework: info

server:
  port: 9090

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html