spring:
  application:
    name: discodeit

  profiles:
    active: dev

  sql:
    init:
      mode: always

discodeit:
  storage:
    type: local


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: info

