events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # conf.d의 모든 .conf 파일 포함
    include /etc/nginx/conf.d/*.conf;
}