# nginx/conf.d/default.conf
# 업스트림 서버 정의
upstream backend {
    server app:8080;
}

server {
    listen 80;
    server_name discodeit; # 서버 이름 > 도메인

    location /api/ {
      proxy_pass http://backend;
    }

    location /ws/ {
      proxy_pass http://backend;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

}