# nginx/conf.d/default.conf
# 업스트림 서버 정의
upstream backend {
    least_conn; # 트래픽이 불균형한 실시간 처리에 적합하다고 생각해서
    server app1:80;
    server app2:80;
    server app3:80;
}

server {
    listen 80;
    server_name discodeit; # 서버 이름 > 도메인

    location /api/ {
      proxy_pass http://backend;
      proxy_http_version 1.1;
              proxy_set_header Host $host;
              proxy_set_header Connection '';
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
      proxy_pass http://backend;
      proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_set_header Host $host;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
    }

}