name: Deploy to ECS

on:
  push:
    branches:
      - part2-김경린

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k5f2z7e1

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_URI }}:latest .
          docker tag ${{ vars.ECR_REPOSITORY_URI }}:latest ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ vars.ECR_REPOSITORY_URI }}:latest
          docker push ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Configure AWS credentials for ECS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Render ECS Task Definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs/task-definition.json
          container-name: discodeit-app
          image: ${{ vars.ECR_REPOSITORY_URI }}:latest

      #  aws ecs update-service --desired-count 옵션을 활용하세요.
      - name: Stop current ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER_NAME }} \
            --service ${{ vars.ECS_SERVICE_NAME }} \
            --desired-count 0 \
            --region ${{ vars.AWS_REGION }}

      - name: Deploy updated Task Definition to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task-definition.json
          cluster: ${{ vars.ECS_CLUSTER_NAME }}
          service: ${{ vars.ECS_SERVICE_NAME }}
          wait-for-service-stability: true # 배포 안정화 확인 (헬스체크 통과 시까지 대기)