name: Deploy to AWS ECS

on:
  push:
    branches:
      - release


jobs:
  build-and-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1  # Public ECR 리전 주의!!

      - name: Login to Public ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY_URI }}:latest .
          docker tag ${{ vars.ECR_REPOSITORY_URI }}:latest ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ vars.ECR_REPOSITORY_URI }}:latest
          docker push ${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}

  deploy-to-ecs:
    name: Deploy to ECS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update ECS Service (Stop old service)
        run: |
          aws ecs update-service --cluster ${{ vars.ECS_CLUSTER }} --service ${{ vars.ECS_SERVICE }} --desired-count 0

      - name: Update ECS Task Definition with new image
        run: |
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition ${{ vars.ECS_TASK_DEFINITION }})
          NEW_TASK_DEF=$(echo $TASK_DEF_JSON | jq --arg IMAGE "${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.status,.revision,.taskDefinitionArn,.requiresAttributes,.compatibilities)')
          aws ecs register-task-definition --cli-input-json "$(echo $NEW_TASK_DEF)"

      - name: Update ECS Service with new Task
        run: |
          NEW_TASK_REVISION=$(aws ecs describe-task-definition --task-definition ${{ vars.ECS_TASK_DEFINITION }} | jq -r '.taskDefinition.revision')
          aws ecs update-service --cluster ${{ vars.ECS_CLUSTER }} --service ${{ vars.ECS_SERVICE }} --task-definition ${{ vars.ECS_TASK_DEFINITION }}:$NEW_TASK_REVISION --desired-count 1
